apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiSGluaWFJYmVsIiwicGFzc3dvcmQiOiJnaHBfaHVzVzJHQUg3R2J2RmNxWEZuem9vVFZZMUM5Y253MjBXZWdaIiwiYXV0aCI6IlNHbHVhV0ZKWW1Wc09tZG9jRjlvZFhOWE1rZEJTRGRIWW5aR1kzRllSbTU2YjI5VVZsa3hRemxqYm5jeU1GZGxaMW89In19fQ==
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
